task: header
b2io/base2.io pull request #521
Opened 2021-03-22 21:11 UTC by tborres

Closes [B2-7](https://b2io.atlassian.net/browse/B2-7) #comment

- move nav out of `Layout` and into a `Header` component
- display mobile menu icon on small screen
- responsive header layout
- move Logo to a `LogoIcon` within an `icons` directory
- shift `LogoProps` to be a shared `SvgProps` type

2021-03-22 21:12 UTC, tborres commented on src/components/Header.tsx
> +`;
I don't love how this jumps around with the screen size changing.

2021-03-22 22:06 UTC, chriswhawkins commented on src/components/Header.tsx
> +const Container = styled.header`
Consider moving the gradient effect to a pseudo-element, or using some other (theme driven? 🤔) mechanism for max-width on the contents.

![image](https://user-images.githubusercontent.com/5854660/112063948-9807a780-8b38-11eb-9dc2-d9955f425704.png)

2021-03-24 18:43 UTC, tborres commented on README.md
> -     - **story:** A user-focused feature written as a user story.
💬 Just misc auto formatting corrections in this file.

2021-03-24 18:43 UTC, tborres commented on package.json
> +    "normalize.css": "^8.0.1",
💬 normalize and reset css to remove browser defaults like 8px padding on body.

2021-03-24 18:43 UTC, tborres commented on package.json
> +    "react-use": "^17.2.1",
💬 Used for `useLockBodyScroll` in the mobile menu.

2021-03-24 18:43 UTC, tborres commented on package.json
> +    "typescript": "^4.2.3"
💬 Typescript update was needed to avoid type errors with the `react-use` library.

2021-03-24 18:43 UTC, tborres commented on src/components/Header.tsx
> +const Container = styled.header`
The clipping problem is no longer an issue now that the css has been normalized and the gradient has been moved. I do think that we'll want to store the gradient and/or max-width in the theme or a global file, but I don't feel comfortable enough with the design files at this point to find a good home for them.

2021-03-24 18:43 UTC, tborres commented on src/components/Layout.tsx
> +          max-width: 1600px;
💬 This max-width and margin-top will need to be reconsidered at a global level, but I think it's ok to move forward as is.

2021-03-25 13:35 UTC, k8hansen commented on src/components/MobileMenu.tsx
> +  .visible & {
@chriswhawkins, should we be using Aria hidden/expand attributes instead of straight classes for something like this?

2021-03-25 13:37 UTC, k8hansen commented on src/components/MobileMenu.tsx
> +  transition: transform 100ms ease-in-out;
```suggestion
  transition: transform 220ms ease-out, opacity 220ms ease-out;
```
I'm not loving this fix either, but I think it is improved just visually. I would appreciate someone else's opinion on making this animation a little smoother.

2021-03-25 13:42 UTC, k8hansen reviewed
Minor animation suggestions, but my bigger suggestion would be using aria attributes for menu toggling instead of classes.

2021-03-25 13:48 UTC, k8hansen commented on src/components/MobileMenu.tsx
> +  position: fixed;
```suggestion
  opacity: 0;
```
begin opacity at zero before updated transition below.

2021-03-25 13:49 UTC, k8hansen commented on src/components/MobileMenu.tsx
> +
```suggestion
opacity: 0;
```
I believe you need to add this as a baseline before applying transition below

2021-03-25 13:50 UTC, k8hansen commented on src/components/MobileMenu.tsx
> +  }
```suggestion
  }
  opacity: 1;
```

2021-03-25 13:52 UTC, k8hansen commented on src/components/MobileMenu.tsx
> +  }
```suggestion
opacity: 1;
    }
```

2021-03-25 21:02 UTC, tborres commented on src/components/MobileMenu.tsx
> +
I think that it would depend on what we want to do with the transition. Currently the transition is just a scale up from 0 (the text is a fade in, which is separate). Adding this opacity line causes the menu to never show (unless we also want to transition the opacity up to 1).

2021-03-27 02:26 UTC, FrankyMartz commented on src/pages/_app.tsx
> +                padding: 0;
Recommend against globally defaulting HTMLElements to a zero padding. Have personally found least resistance using the Normalize.CSS library instead of outright starting from zero, as CSS resets require more intensive testing on far more clients.

2021-03-27 03:31 UTC, FrankyMartz commented on src/components/Header.tsx
> +  ${atMd} {
Coolio, 👍🏽 . We will have to adjust menu item spacing and sizes but definitely a solid kick-off.

2021-03-27 03:54 UTC, FrankyMartz requested changes
It looks like the Mobile menu disappears, because the header width grows beyond the widget boundary.
<details>
<summary>Click here to view</summary>
<img width="397" alt="Screen Shot 2021-03-26 at 10 24 27 PM" src="https://user-images.githubusercontent.com/1040118/112708975-949b5580-8e83-11eb-8c30-1769be732b48.png">
</details>

In terms of menu animation, I suggest one of two patterns (I'll expand on second option further down). For right now though, we should pick a single axis (x,y) and "Slide-in" on that axis. So for instance, menu button click may slide the menu backdrop (top -> bottom) or (right -> left).
 The reason for this is both simplicity and perception. A moving edge corner-to-corner reads uncomfortable (sharp edges), and we want to use a motion the user is familiar with like blinds, door, etc because this "feels" inviting. The other note, is that even if a corner-to-corner animation may have the same duration as a single axis motion. The perceived distance to travel in corner-to-corner feels longer. We do want to transition the menu in but we don't want the user to feel as though they have to wait for it (even if they actually aren't).
 
On other concept: I've been playing around with the idea smart glass. There's this special glass that exists that is transparent by default but when the space requires privacy, isolation the glass will blur-in as frosted.  I've been playing with this idea, envisioning this for our menu as it could animate relative quickly and lack of distance to travel would reduce perceived duration.

2021-03-29 12:51 UTC, k8hansen commented on src/pages/_app.tsx
> +                padding: 0;
Interesting!

2021-03-31 03:07 UTC, FrankyMartz commented on package.json
> +    "normalize.css": "^8.0.1",
We should really include NodeJS version.
```json
  "engines": {
    "node": "^15.12.0",
    "npm": "^7.6.3"
  }
```
Have noticed with last few clean `npm install`'s that the  `package-lock.json` file is updating.  This should not happen when a `package-lock.json` is committed to the repository. The only time that happens is when there is significant difference in NodeJS versions utilized between developers or a npm package was removed/added.

2021-03-31 03:47 UTC, FrankyMartz commented on src/components/Layout.tsx
> +          max-width: 1600px;
When it comes to adaptive layouts, you want to avoid introducing axis limitations in children (explicit width/height) and instead use relative portions — i.e. percentages where possible. The concept being each child element should only concern itself with accommodating itself within the space allotted by its parent, and should not concern itself with the explicit dimensions/limitations of that parent.

 <details>
 <summary>Click here to view example</summary>
<img width="568" alt="Screen Shot 2021-03-30 at 10 32 34 PM" src="https://user-images.githubusercontent.com/1040118/113087188-b741ad00-91a8-11eb-9eb5-209d875d360c.png">
</details>
  
  In order to prevent un-viewable overflow on the page you would use closest element near `body` or in rare cases `body` to establish `max-width/min-width` limitation.

2021-03-31 03:52 UTC, FrankyMartz commented on src/components/Header.tsx
> +  width: 100vw;
This element should span the width of the parent, ideally `main` in a `body -> main` configuration. Using an explicit width here is likely to introduce issues down the line as `100vw` may not be possible should it's ancestors introduce padding/margins.

2021-03-31 04:06 UTC, FrankyMartz commented on src/components/Header.tsx
> +  width: 100vw;
This is currently not achieving full width span in tablet views due to `max-width` implementation in child element `<Content>`. Also, recommend using `100%` vs `100vw`; since in some situations `vw` includes scrollbars in width calculation resulting in unintended horizontal scroll.

2021-03-31 04:27 UTC, FrankyMartz requested changes
The doesn't span full width on smaller devices. This should be addressed.
<details>
<summary>Click here to view</summary>
<img width="698" alt="Screen Shot 2021-03-30 at 11 21 55 PM" src="https://user-images.githubusercontent.com/1040118/113090205-e0653c00-91ae-11eb-9632-c662b3829f71.png">
</details>

The sidebar animation is much better 👍🏽 !
We may eventually want to include an animation to hide menu instead of simply having it disappear, but that can be tweaked later.

2021-03-31 12:23 UTC, tborres commented on package.json
> +    "normalize.css": "^8.0.1",
The primary driver of the lock file being updated recently is the addition of the normalize.css package. Let's chat about locking the node version and which version to lock it to. I can see benefits of locking it tightly to a version to reduce potential differences between machines, but that is at the cost of forcing contributors on the team to switch their node version often while dipping into the project from their other projects.

2021-03-31 12:40 UTC, tborres commented on src/components/Header.tsx
> +  width: 100vw;
🙁 I had switch from `100%` to `100vw` to try to resolve the "header width grows beyond the widget boundary" issue, but I think the header growing is more of a consequence of the crazy font sizes that are currently in the main body of the site rather than an issue with the header. For instance, when I greatly increase the font sizes on the Bootstrap site it has the same type of header sizing issue.

I'll switch it back to 100% and then address the sizing issues at a future time if they continue when we have real content. However, I'm open to specific recommended solutions.

2021-03-31 17:25 UTC, merged