B2 71 add gradient
b2io/base2.io pull request #546
Opened 2021-04-26 13:20 UTC by asingleton6

2021-04-26 18:08 UTC, nelsW70 commented on src/components/pages/home/FeaturedCaseStudy.tsx
> +      <TextContainer
@asingleton6, I'd probably move these two rules into the styled component itself to keep things clean but not sure what the seniors think

Also, not sure how others approach this but I'd rather see z-index values be as low as possible and only as much as is necessary to increase hierarchy over other elements in the DOM. Generally increasing in single increments.

So like, element A has z-index: 1, element B has z-index: 2, etc.  Otherwise, you get into the z-index: 1,000,000 real quick

2021-04-26 18:57 UTC, tborres reviewed
The gradient looks pretty good. The Zeplin version seems to have some sort of noise to it, but I'm not sure how that would be applied. I'd like to get @chriswhawkins eyes on it from a visual and CSS standpoint. I'm not sure if any of those rgb colors match up to our color palette. If so then we'll when to drive those off the theme.

In addition to the comments that I added to the source I think that we'll need to introduce a sizing mechanism to ensure that the contents of gradient don't bleed outside of the pane's container. We could add more spacing on the home page, but in general I've been thinking of it as though each pane should fully contain itself (unless it's visuals need to overlap other pane content).

Aside from the source code changes, take a look at the [Development Workflow](https://github.com/b2io/base2.io/tree/next#readme) in the next branch's README when you get a chance.. With Jira being newish for all of us I detailed a suggested card management and PR process there.

2021-04-26 18:57 UTC, tborres commented on src/components/pages/home/FeaturedCaseStudy.tsx
> +  width: calc(100% + (2 * 1.5rem));
🔧 There's a handful of places in this `Gradient` that have spacing values that match the `spacing.ts` file. Consider leveraging the theming in those cases.

e.g. (note that you'll need to `import { spacing } from '~/theme/spacing';` for this usage.

```suggestion
  width: calc(100% + (2 * ${spacing.sm}));
```

2021-04-26 18:57 UTC, tborres commented on src/components/pages/home/FeaturedCaseStudy.tsx
> +      <TextContainer
I agree with Nelson. z-index value picking is always fun. Generally I think that it should be as low as possible unless it has a functional reason to be a larger number (such as for a header or modal windows).

2021-04-26 19:33 UTC, asingleton6 commented on src/components/pages/home/FeaturedCaseStudy.tsx
> +      <TextContainer
Changes have been merged!

2021-04-26 20:55 UTC, mewdriller commented on src/components/pages/home/FeaturedCaseStudy.tsx
> +  background: linear-gradient(
🤔 This might be a candidate for either [`polished`'s `linearGradient` helper](https://polished.js.org/docs/#lineargradient) or the `interpolateColors` helper on my branch (although that only currently works on colors w/o an alpha channel).

That would allow us to use `theme` colors for the start/stop and compute the between steps.

2021-04-26 20:55 UTC, mewdriller commented on src/components/pages/home/FeaturedCaseStudy.tsx
> +// The gradient will overlap the "Built for Results" component, on desktop, until padding is added between each sections
❓ Do we have a follow-up card to remove this once the trigger condition ("padding is added...") is met?

2021-04-26 20:55 UTC, mewdriller commented on src/components/pages/home/FeaturedCaseStudy.tsx
> +  z-index: 1;
⚠️ There's some general _issues_ with the `z-index` organization in the site at this point. I think we need to align on some "depths" for things to sit at by default so we can add these background elements without colliding with content above/below.

![image](https://user-images.githubusercontent.com/492553/116149212-dbad7e00-a6af-11eb-85c6-44c06502a3c2.png)

2021-04-26 20:55 UTC, mewdriller commented on src/components/pages/home/FeaturedCaseStudy.tsx
> +  z-index: 1;
🤔 Also, (totally subjectively) the horizontal edges of that gradient look *sharp* to me. Seems like _maybe_ it should have a bit of blending on those edges as well? That could be just a biproduct of the overlap though. 🤷

2021-04-27 15:14 UTC, asingleton6 commented on src/components/pages/home/FeaturedCaseStudy.tsx
> +  z-index: 1;
@mewdriller @tborres 
I updated the gradient to be contained inside the parent container on desktop! Do the edges still look too sharp??

![Screen Shot 2021-04-27 at 11 01 04 AM](https://user-images.githubusercontent.com/5387554/116264008-eae00a80-a747-11eb-9690-125f5cbfed5f.png)

2021-04-27 15:19 UTC, asingleton6 commented on src/components/pages/home/FeaturedCaseStudy.tsx
> +  background: linear-gradient(
I'll add a card in Jira to add this. Thanks Drew!

2021-04-27 20:14 UTC, tborres requested changes
It looks like the gradient is escaping the container on the bottom when between a mobile and tablet breakpoint (e.g. 700px). This may be due to the `height: 123%`, but I'm not sure. May need to add a calculated min-height to ensure that it doesn't collide with other panes.

Once the sizing issue is addressed it should be good to merge and then begin work on the home page layout task while improving the smoothness of this gradient in a separate task.

![image](https://user-images.githubusercontent.com/2048050/116306663-5a1f2400-a773-11eb-9d4e-f34970963c29.png)

2021-04-28 17:50 UTC, asingleton6 commented
@mpcondo 
Thank you!! ☺️  

I noticed in the mockup that the gradient actually flows past the picture, throwing off the balance. 
https://zpl.io/V1RyNQB

<img width="438" alt="Screen Shot 2021-04-28 at 1 47 18 PM" src="https://user-images.githubusercontent.com/5387554/116449958-bd1ec280-a828-11eb-88fb-e00fce9198a2.png">

2021-04-28 17:52 UTC, nelsW70 commented
Looks good to me! I think Tony's comment about smoothing the gradient blend out in another task makes sense. That's really the only thing I notice that hasn't already been addressed. 

Nice work Ashley!

2021-04-28 18:33 UTC, tborres approved these changes
Nice job 👍

2021-04-28 19:07 UTC, merged