Add Our Culture & Beliefs content to Culture page
b2io/base2.io pull request #567
Opened 2021-05-13 16:55 UTC by mewdriller

B2-89

2021-05-13 18:40 UTC, tborres reviewed
We may want to huddle up to discuss consistency. The Our Culture is essentially the same structure as How We Engage, but the approach and some of the elements are different. I'm not sure what the "right" way should be, but they probably shouldn't be different.

I noticed at the mid-range size (I tested at 1024px) the text content layout is more narrow than the other text on the page. This is probably because it's tied to the column layout which didn't have enough room to kick into 2 columns yet.

![image](https://user-images.githubusercontent.com/2048050/118170865-9a7bd480-b3f8-11eb-8cdd-f0385dec40d9.png)

2021-05-13 18:40 UTC, tborres commented on src/components/CulturePage/OurCulture.tsx
> +        gap: 6rem;
🎨 If we're trying to match the comps I'm not sure if we can use the `gap` approach unless we add another wrapper around the icon card list. The mobile comp (375px) has the space between the top text and the card list as 5rem, and the space between each card as 4rem. Current implementation has it all at 6rem.

🔤 
`gap` should come before `grid-template-columns`

2021-05-13 18:40 UTC, tborres commented on src/components/CulturePage/OurCulture.tsx
> +        <Text as="p" variant="h3">
💬 `Text` is `p` by default so we shouldn't need to specify it here; however, that does call out that this is a `p`, which I think some other similar panes have it as an h3. `p` is probably more appropriate, and we'll have to create a clean-up card to ensure that we're being consistent across the board.

2021-05-14 12:59 UTC, mewdriller commented
> We may want to huddle up to discuss consistency. The Our Culture is essentially the same structure as How We Engage, but the approach and some of the elements are different. I'm not sure what the "right" way should be, but they probably shouldn't be different.
> 
> I noticed at the mid-range size (I tested at 1024px) the text content layout is more narrow than the other text on the page. This is probably because it's tied to the column layout which didn't have enough room to kick into 2 columns yet.
> 
> ![image](https://user-images.githubusercontent.com/2048050/118170865-9a7bd480-b3f8-11eb-8cdd-f0385dec40d9.png)

Sounds good. I'll try to drop in on the post-coffee base2.io chat this morning.

2021-05-14 13:00 UTC, mewdriller commented on src/components/CulturePage/OurCulture.tsx
> +        gap: 6rem;
Yeah. I eye-balled it and thought that it was visually consistent at an even `6rem`. There's actually a ~`9rem` horizontal gap in the columns (vs ~`6rem` on the rows) in the desktop size as well. I'll add in the exact values for all the scenarios.

2021-05-14 13:01 UTC, mewdriller commented on src/components/CulturePage/OurCulture.tsx
> +        <Text as="p" variant="h3">
I knew it was defaulting to `p` but I felt like adding the explicit `as="p"` made it clearer to someone coming after while not adding too much cruft. 🤷

2021-05-16 14:34 UTC, tborres requested changes
The `IconCardGrid` doesn't appear to be tiling correctly at the tablet size. Since Culture doesn't have a comp at that size you can use the Approach page comps and components as a visual guide.

2021-05-16 14:34 UTC, tborres commented on src/components/IconCard.tsx
> +    <ul
At tablet size the IconGrid should be displaying in 2 columns

![image](https://user-images.githubusercontent.com/2048050/118400741-eadd7700-b630-11eb-99ba-268c6ff7c672.png)

2021-05-16 14:34 UTC, tborres commented on src/components/ApproachPage/index.tsx
> +        css={css`
⚠️ Ashley has a PR out for approach layout (#568) that may collide with this.

2021-05-18 15:06 UTC, nelsW70 approved these changes

2021-05-18 15:07 UTC, nelsW70 commented
Woohoo, so nice to see it coming together!

2021-05-18 15:58 UTC, merged