B2 15 approach layout
b2io/base2.io pull request #568
Opened 2021-05-13 20:20 UTC by asingleton6

[B2-15](https://b2io.atlassian.net/browse/B2-15)
- Add appropriate spacing between sections
- Change the breakpoint for desktop from 1600px to 1200px

Mobile: https://zpl.io/VQ607v5
Tablet: https://zpl.io/2G8EwDJ
Desktop: https://zpl.io/a7XkEpp
Extra Wide Desktop: https://zpl.io/25QE9PW

2021-05-14 12:35 UTC, nelsW70 commented
This looks great Ashley, it's awesome to see it coming together! 

The only thing I'm seeing is that the margin-bottom clamp on HowWeBuild might need another value after 'tablet' as it's too snug against QuotedImage at 1200 and above. 

![Screen Shot 2021-05-14 at 8 29 40 AM](https://user-images.githubusercontent.com/17680907/118271401-37894c80-b48f-11eb-96c7-465b8fdd7b28.png)

![Screen Shot 2021-05-14 at 8 28 50 AM](https://user-images.githubusercontent.com/17680907/118271402-3821e300-b48f-11eb-9fa2-89fe7373cbb4.png)

2021-05-14 12:35 UTC, nelsW70 approved these changes

2021-05-14 13:16 UTC, tborres requested changes
This is looking really good. Little tweaks:

- adjust `p` weight to 300 in the typography file
- mobile CTA seems too low
- in the 1600 comps the How We Build image should still be touching the far left, and the quote image should be touching the far right
- Starting at 1080 there should be more space between How We Build and the quote

2021-05-14 13:16 UTC, tborres commented on src/components/ApproachPage/index.tsx
> +import { cssClamp, atMinTablet, spacing } from '~/theme';
🔤 

```suggestion
import { atMinTablet, cssClamp, spacing } from '~/theme';
```

2021-05-16 13:05 UTC, tborres approved these changes
Looks great 🌹

2021-05-16 13:27 UTC, tborres commented on src/components/ApproachPage/HowWeBuild.tsx
>    }
🔧 ☝️ A bit above this line there is a `:nth-child(odd)` that is throwing warnings at build time because `The pseudo class ":nth-child" is potentially unsafe when doing server-side rendering. Try changing it to ":nth-of-type"`. It makes sense to make that change in this PR.

2021-05-17 14:18 UTC, asingleton6 commented on src/components/ApproachPage/HowWeBuild.tsx
>    }
Done!

2021-05-17 14:30 UTC, merged