Improve between-page font performance
b2io/base2.io pull request #571
Opened 2021-05-18 14:17 UTC by mewdriller

- Convert ttf to woff2
- Add a preload link for the font file

B2-87

2021-05-18 14:20 UTC, mewdriller commented
🤔 This cleans up the immediate issue and cuts the font size by ~60%, but we can probably get further perf gains by subsetting (only include the characters we use) the font. I was hesitant to do that in here since it seems like _some_ of the tools for subsetting can mess up the axes in variable fonts.

I think it probably makes sense to create a follow-up card to do that.

2021-05-18 14:42 UTC, nelsW70 commented
@mewdriller, to get access to "font-style: italic" would we convert RoobertItalicGX.ttf to woff2 and include it in the globally below the existing font-face?

Italics are being used in the design on the Approach page in the QuotedImage component

2021-05-18 14:43 UTC, nelsW70 approved these changes

2021-05-18 15:04 UTC, asingleton6 approved these changes
This looks great! It looks great on both Mac and Windows computer too.

2021-05-18 15:39 UTC, tborres requested changes
This looks great. I'm only flagging this as Request changes because of Nelson's catch on the italics missing. Once that's corrected this will be ready to ship.

2021-05-18 15:39 UTC, tborres commented on src/pages/_document.tsx
> +                src: url(/RoobertGX.woff2) format('woff2-variations');
❓ Just curious, was the switch to woff2 for performance reasons or implementation?

2021-05-18 15:40 UTC, tborres commented
Should the font loading for Storybook be changed too?

2021-05-18 17:12 UTC, mewdriller commented on src/pages/_document.tsx
> +                src: url(/RoobertGX.woff2) format('woff2-variations');
It's a better (more modern) format. It's ~60% smaller than the comparable `ttf`.

2021-05-18 17:39 UTC, mewdriller commented
> @mewdriller, to get access to "font-style: italic" would we convert RoobertItalicGX.ttf to woff2 and include it globally below the existing font-face in src/pages/_document.tsx?
> 
> Italics are being used in the design on the Approach page in the QuotedImage component

Good catch on the italic issue! After digging in, the variable font _only_ has an axis for weight and not slant. 😢

I ended up needing to convert the italic `ttf` to `woff2` and include that as well. Not ideal, but I think it's the best we can do for now at least.

2021-05-18 17:40 UTC, merged

2021-05-19 17:53 UTC, mewdriller commented
> Should the font loading for Storybook be changed too?

Missed this in the feedback. Yes, it should. I'll add a card and tackle that now.