B2 95 masked images
b2io/base2.io pull request #590
Opened 2021-08-03 17:56 UTC by laurapadilla

2021-08-04 14:55 UTC, k8hansen commented on src/theme/colors.ts
> +//  export const gradient = {
remove

2021-08-04 15:02 UTC, k8hansen requested changes
Remove the team image files that did not have changes, except for Zach's image (name change) and the noise image can stay.

Looks like the gradient could use a wee bit more tweaking to get more red happening.

2021-08-04 16:38 UTC, laurapadilla commented
I tweaked the gradient but it doesn't look 100% on images with black background. I also tweaked some of the spacing to match the Zeplin comp (adjusted the top and left margins of the team member name)

2021-08-05 15:03 UTC, k8hansen reviewed
The images are showing changes because we had originally uploaded the edited files form Zeplin (that BFR had put actual masks/effects on). I changed them to the original image files so that those effects  could be implemented through CSS.

2021-08-05 17:15 UTC, k8hansen reviewed
This is really close, I think it'd be better with a WEE little bit more red? If that is not possible, that's ok.

The bigger issue though is the contrast with Franky's image still. Would you be able to add a little bit of an extra dark blue gradient to the bottom of his image only? I'm meaning even doing this in photoshop and re-uploading, it just needs a bit more contrast to see his name. 

Or, if possible, increase that dark blue gradient a notch or two to make all of the images a little more contrast-y.

Spacing changes look great!

2021-08-06 19:29 UTC, laurapadilla commented
1. Added a little more red to images. 
2. Added a gradient to Frankie's image so his name stands out more

2021-08-09 14:14 UTC, k8hansen commented on src/components/TeamMemberCard.tsx
> +            linear-gradient(322deg, rgba(15,13,52,0.83), rgba(246,58,82,0.85));
I would change that last gradient transparency to 0.60 instead of 0.85, I'm not sure if that's what you had it at previously, but that looks the closest to me.

2021-08-09 14:14 UTC, k8hansen approved these changes
Just that one change to the gradient and then good to go!

2021-08-09 14:24 UTC, laurapadilla commented on src/components/TeamMemberCard.tsx
> +            linear-gradient(322deg, rgba(15,13,52,0.83), rgba(246,58,82,0.85));
Done!

2021-08-09 14:26 UTC, merged