b2-122-404/500-page-finesse-and-creation
b2io/base2.io pull request #610
Opened 2021-08-19 16:13 UTC by ewaight12

feat(error-pages): 404/500 Page Finesse and Creation
- Closes [b2-122](https://b2io.atlassian.net/browse/B2-122)
- Added custom pages for 400 and 500 errors

2021-08-19 19:25 UTC, k8hansen commented on src/theme/typography.ts
> +    marginBottom: spacing.xs,
great catch!

2021-08-19 19:54 UTC, ewaight12 commented on src/theme/typography.ts
> +    marginBottom: spacing.xs,
Thanks for catching that I will fix!

2021-08-19 21:16 UTC, mewdriller requested changes

2021-08-19 21:16 UTC, mewdriller commented on src/components/Custom404Page/index.tsx
> +					<Text as="li" variant="li"><Link href="/" variant="CTA">Home</Link></Text>
⚠️ There isn't an `li` variant for `Text` so I think these nodes can just be `<Text as="li" />`.

2021-08-19 21:16 UTC, mewdriller commented on src/components/Custom404Page/index.tsx
> +					${atMinXL} {
💭 Rather than doing individual spacing between each like this at a particular breakpoint, it could be easier/cleaner to do something with `gap` for either `display: grid` or `display: flex`. Maybe something like:

![image](https://user-images.githubusercontent.com/492553/130144107-f9a3415d-7fda-4aab-a6ab-7f701ac1768e.png)

![image](https://user-images.githubusercontent.com/492553/130144135-5d7a1d52-cf50-42d6-bac9-0180cd08cf93.png)

2021-08-19 21:16 UTC, mewdriller commented on src/components/Custom500Page/index.tsx
> +					margin-left: ${spacing.marginXl};
🔁 Similar comment as before RE ad-hoc spacing.

![image](https://user-images.githubusercontent.com/492553/130145218-cbcfb027-4ccb-4a60-907b-ee3d12d6d151.png)

![image](https://user-images.githubusercontent.com/492553/130145239-7d338bb1-4607-4fd0-8d1f-9131acd1cd1f.png)

2021-08-19 21:16 UTC, mewdriller commented on src/components/Custom500Page/index.tsx
> +					margin-left: ${spacing.marginXl};
☝️ Note: The `target` + `rel` bits will need to either wait for @laurapadilla's change to `Link`'s prop type or you'll need to replicate that change yourself.

2021-08-20 20:21 UTC, ewaight12 commented on src/theme/typography.ts
> +    marginBottom: spacing.xs,
@k8hansen This should be fixed, thanks

2021-08-23 20:51 UTC, k8hansen approved these changes
I reviewed all of Drew's notes as well as mine. LGTM! :shipit:

2021-08-23 22:55 UTC, merged