feat(work-page): Work page content & layout
b2io/base2.io pull request #627
Opened 2021-08-31 23:42 UTC by ewaight12

- Closes [#b2-25](https://b2io.atlassian.net/browse/B2-25)
- Added shared component for case study preview
- Added content for work page

Issues:
- Typescript error on line 19 of CaseStudyPreview.tsx not sure the proper way to fix feedback would be great

2021-09-01 14:33 UTC, laurapadilla reviewed
Looks good! Only 2 callouts is that the AEP ScopeBuilder image looks a little squished, and that the left/right margins on the page as a whole are a little bigger than the comp, but I could be mistaken!

Site:
<img width="1790" alt="Screen Shot 2021-09-01 at 10 32 46 AM" src="https://user-images.githubusercontent.com/19558580/131690254-55897ce7-83e3-4b25-a291-9eca4927941b.png">

Comp:
<img width="1687" alt="Screen Shot 2021-09-01 at 10 32 17 AM" src="https://user-images.githubusercontent.com/19558580/131690182-970fe9fd-9b8d-47d4-94b8-46c1798db496.png">

AEP ScopeBuilder:
<img width="702" alt="Screen Shot 2021-09-01 at 10 24 59 AM" src="https://user-images.githubusercontent.com/19558580/131690352-38475972-ee75-4d4b-b039-9d0756ed5ba3.png">

2021-09-01 14:45 UTC, k8hansen commented on src/components/ScopeBuilderPage/index.tsx
> +  // Add description
Can delete

2021-09-01 19:55 UTC, k8hansen commented
Similar feedback to Laura's, the top/bottom margin on the header can be smaller. I would go with this `xxl2` from the comp. But this looks fantastic considering we don't really have comps for larger screen sizes. Approved with that revisitation.

<img width="1038" alt="Screen Shot 2021-09-01 at 3 52 48 PM" src="https://user-images.githubusercontent.com/13206464/131735481-731bd578-1d17-4395-88c0-cda2842636bb.png">

2021-09-01 19:57 UTC, k8hansen approved these changes

2021-09-01 20:38 UTC, mewdriller requested changes

2021-09-01 20:38 UTC, mewdriller commented on src/components/WorkPage/CaseStudyPreview.tsx
> +};
🚨 Looks like the build is broken due to an error in here: 

![image](https://user-images.githubusercontent.com/492553/131737114-f62a7ae5-44bf-4b4c-8420-bc85329b417b.png)

You can check this locally with `npm run build`.

2021-09-01 20:38 UTC, mewdriller commented on src/components/WorkPage/CaseStudyPreview.tsx
> +};
⚠️ Looks like our linting isn't catching alpha-order on our TS types. Maybe that's something we can look into in another card to automate, but we can fix manually for now?

2021-09-01 20:38 UTC, mewdriller commented on src/components/WorkPage/CaseStudyPreview.tsx
> +      <ResponsiveImage alt={alt} src={src} />
⚠️ It looks like we're not getting any value  in encapsulating this as a local component. It's only used once and probably just adds mental overhead to the file. I think we can just inline the `next/image` here without the wrapping `div`.

2021-09-01 20:38 UTC, mewdriller commented on src/components/WorkPage/CaseStudyPreview.tsx
> +          ${atMinTablet} {
💭 Maybe a newline here between the base styles and the media query.

2021-09-01 20:38 UTC, mewdriller commented on src/components/WorkPage/CaseStudyPreview.tsx
> +          ${atMinSm} {
💭 The `sm` breakpoint is actually smaller than the `tablet` one. Maybe it would make more sense to have the `sm` styles before the `tablet` ones to mimic the mobile-first setup in how you scan the styles?

2021-09-01 20:38 UTC, mewdriller commented on src/components/WorkPage/CaseStudyPreview.tsx
> +          `}
⚠️ Alpha-order on props is off here. I _think_ @JaviAir had this resolved in his updates to the `eslint` setup, but maybe not if this wasn't yelling at you.

2021-09-01 20:38 UTC, mewdriller commented on src/components/WorkPage/index.tsx
> +          src={require('./images/net-jets.jpg')}
💭 It's a small thing, but probably `netjets.jpg` is a better name. I doubt they'd ever actually look at the filename, but they don't lowercase their name with a hyphen like that.

2021-09-01 20:38 UTC, mewdriller commented on src/components/WorkPage/CaseStudyPreview.tsx
> +            & p::before {
💭 I _think_ the `&` is extraneous here? And, if you want, you could consider nesting the `&::before` inside the `p` style block.

2021-09-01 20:38 UTC, mewdriller commented on src/components/WorkPage/index.tsx
> +        css={css`
🔁 Same comment as before RE alpha-order.

2021-09-01 20:38 UTC, mewdriller commented on src/components/WorkPage/index.tsx
> +          ${atMinTablet} {
🔁 Same comment as before RE newline for readability.

2021-09-01 20:38 UTC, mewdriller commented on src/components/WorkPage/index.tsx
> +            }
⚠️ I think these should be collapsed into one `> *:nth-of-type(2n)` selector here?

2021-09-01 20:38 UTC, mewdriller commented on src/components/WorkPage/index.tsx
> +          display: grid;
💭 Maybe a newline after vars?

2021-09-01 20:38 UTC, mewdriller commented on src/components/WorkPage/index.tsx
> +          link="netjets"
🔁 Same comment as before RE alpha-order.

2021-09-01 20:38 UTC, mewdriller commented on src/components/WorkPage/index.tsx
> +          link="scopebuilder"
🔁 Same comment as before RE alpha-order.

2021-09-01 20:38 UTC, mewdriller commented on src/components/WorkPage/index.tsx
> +          link="batteryxt"
🔁 Same comment as before RE alpha-order.

2021-09-01 20:38 UTC, mewdriller commented on src/components/WorkPage/CaseStudyPreview.tsx
> +  link: string;
💭 Maybe we should rename this as `href` to be more clear what the intent of it is? And I think we should probably have consumers of the component put in the full path to the case study instead of just the last bit. That will make it more flexible if we change up where we keep those in the future; e.g.: `href="/work/batteryxt"` instead of `href="batteryxt"`.

2021-09-02 00:58 UTC, ewaight12 commented on src/components/WorkPage/CaseStudyPreview.tsx
> +};
Looks like this might be the best option to enforce sorting props., let me know what you think https://www.npmjs.com/package/eslint-plugin-react

2021-09-03 01:13 UTC, merged