WIP: Add seo tags for careers/blog/work pages
b2io/base2.io pull request #630
Opened 2021-09-01 15:24 UTC by laurapadilla

Add SEO description tags for Careers, Blog and Work pages. Looking for feedback on the copy I used, especially for Blog!

2021-09-01 20:10 UTC, k8hansen commented on src/components/CareersPage/index.tsx
>    // TODO: Add description for CareersPage.
🔁

2021-09-01 20:11 UTC, k8hansen commented on src/components/WorkPage/index.tsx
>    // TODO: Add description for WorkPage.
🔁

2021-09-01 20:14 UTC, k8hansen commented on src/components/CareersPage/index.tsx
> +    <Layout description="Working at Base Two" title="Careers">
Should this include more accurate SEO descriptions like "jobs", "career", or "employment"? This might be a question for @chriswhawkins

2021-09-01 20:14 UTC, k8hansen commented on src/components/WorkPage/index.tsx
> +      description="Unique challenges
Should this be more descriptive? Should we include the words "portfolio" or "worksamples" here? Again, might be a question for Chris.

2021-09-01 20:16 UTC, k8hansen requested changes
This might be worth a mini-meeting, I think we can improve our SEO meta tags. I know you were likely just basing these off of what we did for previous pages.

2021-09-02 20:23 UTC, laurapadilla commented
Took another stab at writing the SEO description tags! Would love your input on this @chriswhawkins!

2021-09-10 15:31 UTC, k8hansen commented on src/components/BlogPage/index.tsx
> +    <Layout description="Blog" title="Blog">
Sorry to be nit-picky, but this should probably say something more than just "blog". Even just "Base Two's blog". I'm trying to think of something that would look good in a link share and I'm coming up blank.

2021-09-10 15:31 UTC, k8hansen approved these changes
Approved with that one minor blog description change. Thanks!

2021-09-10 19:07 UTC, laurapadilla commented on src/components/BlogPage/index.tsx
> +    <Layout description="Blog" title="Blog">
Okay I updated to something a little more descriptive, but I think we can change it if/when we start working in the Blog!

2021-09-10 19:09 UTC, merged