B2 39 careers page layout
b2io/base2.io pull request #635
Opened 2021-09-17 18:49 UTC by laurapadilla

Careers Page:
1. **Add basic layout + content** ([B2-39)](https://b2io.atlassian.net/browse/B2-39?atlOrigin=eyJpIjoiNGE1MzY1MWI4NDQ1NGMwMzlmN2Y3NGQ5MmYyNzEyNTkiLCJwIjoiaiJ9)
2. **Add Position title/description** [(B2-112)](https://b2io.atlassian.net/browse/B2-112?atlOrigin=eyJpIjoiZWNmOTk1ZjM0N2NmNGMxODg3YmNiODFjZmQyNTcwZjciLCJwIjoiaiJ9)
- For the `Apply` button, I imported the `Button` styled component I used for the `Contact` form `submit` button. Should we pull that button out into a separate component like the `Heading` or `Text`?

**3. Add Benefits selector components (desktop + mobile)**[(B2-37)](https://b2io.atlassian.net/browse/B2-37?atlOrigin=eyJpIjoiNDdlYWQ3NTJhMmJlNDkwMWI4NzIwOWQ2ZTI5MjRkZWEiLCJwIjoiaiJ9)
- Looking for feedback on accessibility + architecture/structure of these two components! Hoping @chriswhawkins can take a look at this. 
- Personally I think the should just use the `BenefitsAccordion` for both small and large screens, but I am using a `react-use` hook to show/hide each component based on the media query. Looking for feedback on this approach as well!

2021-09-22 18:51 UTC, mewdriller requested changes

2021-09-22 18:51 UTC, mewdriller commented on src/components/CareersPage/OpenPositions.tsx
> +      {jobs.map((job) => {
🔁 Same comment RE JSON vs JSX for this list of data.

2021-09-22 18:51 UTC, mewdriller commented on src/components/CareersPage/OpenPositions.tsx
> +          <>
⚠️ Looks like this Fragment is extraneous since there's only one child in here.

2021-09-22 18:51 UTC, mewdriller commented on src/components/CareersPage/WorkingAtB2.tsx
> +
🔁 Same comment RE extraneous newline.

2021-09-22 18:51 UTC, mewdriller commented on src/components/CareersPage/index.tsx
> +        <BenefitsAccordion>
⚠️ I think we want to do this with CSS rather than JS so it's safer with SSR. That may mean rendering both of them and hiding/showing with media queries in CSS.

2021-09-22 18:51 UTC, mewdriller commented on src/components/ContactPage/ContactForm.tsx
> +  }
💭 I feel like we already addressed this, and it is needed, but just because I can't get it out of my head: I feel like we _shouldn't_ have to worry about the vendor prefixing here. This may be one of those exceptions though.

2021-09-22 18:51 UTC, mewdriller commented on src/components/CulturePage/OurCulture.tsx
> +        ></IconCard>
🔁 Same comment RE self-closing tags.

2021-09-22 18:51 UTC, mewdriller commented on src/components/CareersPage/Benefits.tsx
> +      <GradientCircle
⚠️ It looks like the positioning might be off on this element:

![image](https://user-images.githubusercontent.com/492553/134403714-dda64892-cb0e-4bc9-92f7-7ae1c009a6f2.png)

2021-09-22 18:51 UTC, mewdriller commented on src/components/CareersPage/index.tsx
> +    <Layout
⚠️ Should the `/careers` page be linked in the global nav or via CTAs anywhere at this point? I'm not seeing that come up in my quick review of the preview URL.

2021-09-22 18:51 UTC, mewdriller commented on src/components/CareersPage/Benefits.tsx
> +      <GradientCircle
☝️ Per our discussion in Slack, I think you're right that it makes sense to use the accordion UX for both desktop and mobile here.

2021-09-29 17:31 UTC, k8hansen approved these changes
On desktop, there is an issue with the accordion where the header is laying over where a click should be landing.

A demonstration is [here](https://youtu.be/faNi2Vf-vr4).

This might not be enough to hold this card up, we should create a bug card and put it in the backlog to resolve this.

![Screen Shot 2021-09-29 at 12 24 04 PM](https://user-images.githubusercontent.com/13206464/135319219-ffbc9d87-5c8d-4918-ac6e-a7f83aed7ec6.png)

I would spend a few minutes trying to see if there is a clear fix for this, if not it's ready to merge, just please create a bug card for the issue. 

Everything else looks fantastic!

2021-09-29 18:09 UTC, merged